export const themeData = JSON.parse("{\"navbar\":[{\"text\":\"首页\",\"link\":\"/\"}],\"sidebar\":{\"/\":[{\"text\":\"示例文档\",\"children\":[{\"text\":\"图表示例\",\"link\":\"/图表示例.md\"},{\"text\":\"Markdown功能示例\",\"link\":\"/Markdown功能示例.md\"},{\"text\":\"SideTable结构对比示例\",\"link\":\"/SideTable结构对比示例.md\"}]},{\"text\":\"内存管理\",\"collapsible\":true,\"children\":[{\"text\":\"01-iOS对象的内存布局\",\"link\":\"/内存管理/01-iOS对象的内存布局.md\"},{\"text\":\"02-isa指针与类对象元类对象的关系\",\"link\":\"/内存管理/02-isa指针与类对象元类对象的关系.md\"},{\"text\":\"03-简述ARC的工作原理\",\"link\":\"/内存管理/03-简述ARC的工作原理.md\"},{\"text\":\"04-循环引用的产生与解决\",\"link\":\"/内存管理/04-循环引用的产生与解决.md\"},{\"text\":\"05-weak和unowned的区别和使用场景\",\"link\":\"/内存管理/05-weak和unowned的区别和使用场景.md\"},{\"text\":\"06-SideTable的结构\",\"link\":\"/内存管理/06-SideTable的结构.md\"},{\"text\":\"07-weak原理\",\"link\":\"/内存管理/07-weak原理.md\"}]},{\"text\":\"锁\",\"collapsible\":true,\"children\":[{\"text\":\"02-iOS中的锁概述\",\"link\":\"/02-iOS中的锁概述.md\"},{\"text\":\"02-优先级翻转问题\",\"link\":\"/锁/02-优先级翻转问题.md\"},{\"text\":\"03-@synchronized原理\",\"link\":\"/锁/03-@synchronized原理.md\"}]},{\"text\":\"UI框架\",\"collapsible\":true,\"children\":[{\"text\":\"01-setNeedsDisplay到屏幕显示的流程\",\"link\":\"/UI框架/01-setNeedsDisplay到屏幕显示的流程.md\"},{\"text\":\"02-UIView绘制显示原理流程解析以及性能优化\",\"link\":\"/UI框架/02-UIView绘制显示原理流程解析以及性能优化.md\"}]},{\"text\":\"绘制\",\"collapsible\":true,\"children\":[{\"text\":\"01-T0代码执行阶段\",\"link\":\"/绘制/01-T0代码执行阶段.md\"},{\"text\":\"02-T1Layout阶段\",\"link\":\"/绘制/02-T1Layout阶段.md\"},{\"text\":\"03-T2Display阶段\",\"link\":\"/绘制/03-T2Display阶段.md\"},{\"text\":\"04-T3Commit阶段\",\"link\":\"/绘制/04-T3Commit阶段.md\"},{\"text\":\"05-T4RenderServer阶段\",\"link\":\"/绘制/05-T4RenderServer阶段.md\"},{\"text\":\"06-T5GPU渲染阶段\",\"link\":\"/绘制/06-T5GPU渲染阶段.md\"},{\"text\":\"07-CPU绘制vsGPU绘制\",\"link\":\"/绘制/07-CPU绘制vsGPU绘制.md\"},{\"text\":\"08-iOS绘制框架分层架构\",\"link\":\"/绘制/08-iOS绘制框架分层架构.md\"}]},{\"text\":\"网络\",\"collapsible\":true,\"children\":[{\"text\":\"01-HTTPS\",\"link\":\"/网络/01-HTTPS.md\"}]}]},\"locales\":{\"/\":{\"selectLanguageName\":\"English\"}},\"colorMode\":\"auto\",\"colorModeSwitch\":true,\"logo\":null,\"repo\":null,\"selectLanguageText\":\"Languages\",\"selectLanguageAriaLabel\":\"Select language\",\"sidebarDepth\":2,\"editLink\":true,\"editLinkText\":\"Edit this page\",\"lastUpdated\":true,\"contributors\":true,\"contributorsText\":\"Contributors\",\"notFound\":[\"There's nothing here.\",\"How did we get here?\",\"That's a Four-Oh-Four.\",\"Looks like we've got some broken links.\"],\"backToHome\":\"Take me home\",\"openInNewWindow\":\"open in new window\",\"toggleColorMode\":\"toggle color mode\",\"toggleSidebar\":\"toggle sidebar\"}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updateThemeData) {
    __VUE_HMR_RUNTIME__.updateThemeData(themeData)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ themeData }) => {
    __VUE_HMR_RUNTIME__.updateThemeData(themeData)
  })
}
